# Nombre del Workflow
name: Build and Deploy to Firebase

# Disparador: Se ejecuta en cada push a la rama 'main'
on:
  push:
    branches:
      - main # Cambia 'main' si usas 'master' u otra rama principal

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Usar치 una m치quina virtual de Ubuntu

    steps:
      # 1. Clona tu repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Usa la versi칩n de Node que necesites

      # 3. Instala las dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # 4. Construye el proyecto de Angular para producci칩n
      - name: Build project
        run: npm run build -- --configuration=production

      # 5. Despliega en Firebase Hosting
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          action: 'deploy'
          project_name: 'apex-raffle' 
          token: ${{ secrets.FIREBASE_TOKEN }}
          channel_id: live 
          only: 'hosting' 